// Generated by CoffeeScript 1.3.3
(function() {
  var PusherServer, pres, pusher_server;

  PusherServer = require('./lib/pusher-server').PusherServer;

  pusher_server = new PusherServer({
    appId: process.env.PUSHER_APP_ID || app_id,
    key: process.env.PUSHER_KEY || pusher_key,
    secret: process.env.PUSHER_SECRET || pusher_secret
  });

  pres = null;

  pusher_server.on('connect', function() {
    pres = pusher_server.subscribe("presence-users", {
      user_id: "system"
    });
    return pres.on('success', function() {
      pres.on('pusher_internal:member_removed', function(data) {
        return console.log("member_removed");
      });
      return pres.on('pusher_internal:member_added', function(data) {
        return console.log("member_added");
      });
    });
  });

  pusher_server.connect();

}).call(this);
